name: MyProject CI/CD
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: your-username/your-java-project
        ref: main
 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
 
    - name: Build with Maven
      run: mvn clean install
 
    - name: Run Tests
      run: mvn test
 
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'
 
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: git clean -fdx
 
  
