name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic versioning tags like v1.0.0, v2.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository (again for the release job)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up GitHub CLI (or any other CLI if you're deploying elsewhere)
      #- name: Set up GitHub CLI
      #  uses: cli/cli-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      # Step 3: Create a release on GitHub (this will use the tag from the push event)
      - name: Create a GitHub Release
        run: |
          TAG_NAME=${github.ref}  # Extract the tag name from the event reference
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
      # Step 5: Notify (optional, e.g., sending a notification or Slack message)
      - name: Send notification about release
        run: |
          echo "Release $TAG_NAME is now live with secret $GITHUB_TOKEN" 
